# Generated by Django 5.0.2 on 2024-02-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=25)),
                ('slide', models.ImageField(upload_to='slider')),
            ],
        ),
    ]
