# Generated by Django 5.0.1 on 2024-02-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0002_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.FileField(max_length=25, upload_to='')),
                ('movie', models.FileField(max_length=25, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='slider',
            name='slide',
            field=models.ImageField(upload_to='movie'),
        ),
    ]
